<?php
declare(strict_types=1);

namespace App\Controller;

use App\Model\Table\UsersTable;
use Notifications\Model\Table\NotificationsTable;
use Notifications\MorphsMany;

/**
 * Notifications Controller
 *
 * @property NotificationsTable|MorphsMany Notifications
 * @property UsersTable Users
 */
class NotificationsController extends AppController
{
    public function initialize(): void
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->Users = $this->getTableLocator()->get('Users');
        $this->Notifications = $this->getTableLocator()->get('Notifications.Notifications');
    }

    public function test() {
        $user = $this->Users->get(1);
        $notification = $this->Notifications->newEntity([
            'type' => 'Test'
        ]);

        $user->notifications = [$notification];

        if (!$this->Users->save($user)) {
            $this->set([
                'success' => false
            ]);
        } else {
            $this->set([
                'success' => true
            ]);
        }

        $this->viewBuilder()->setOption('serialize', ['success']);
    }
}
